### ISSUE TITLE
go get fails

### ISSUE THREAD

**Issue by jpillora** [bcicen/ctop#19] opened 2017-03-10 00:29 UTC
Looks like you need to `vendor/` your deps

```
$ go get -v -u github.com/bcicen/ctop
github.com/bcicen/ctop (download)
github.com/op/go-logging (download)
github.com/fsouza/go-dockerclient (download)
github.com/docker/docker (download)
github.com/docker/go-units (download)
github.com/hashicorp/go-cleanhttp (download)
Fetching https://golang.org/x/net/context?go-get=1
Parsing meta tags from https://golang.org/x/net/context?go-get=1 (status code 200)
get "golang.org/x/net/context": found meta tag main.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/context?go-get=1
get "golang.org/x/net/context": verifying non-authoritative meta tag
Fetching https://golang.org/x/net?go-get=1
Parsing meta tags from https://golang.org/x/net?go-get=1 (status code 200)
golang.org/x/net (download)
Fetching https://golang.org/x/net/context/ctxhttp?go-get=1
Parsing meta tags from https://golang.org/x/net/context/ctxhttp?go-get=1 (status code 200)
get "golang.org/x/net/context/ctxhttp": found meta tag main.metaImport{Prefix:"golang.org/x/net", VCS:"git", RepoRoot:"https://go.googlesource.com/net"} at https://golang.org/x/net/context/ctxhttp?go-get=1
get "golang.org/x/net/context/ctxhttp": verifying non-authoritative meta tag
github.com/gizak/termui (download)
github.com/maruel/panicparse (download)
github.com/mattn/go-runewidth (download)
github.com/mitchellh/go-wordwrap (download)
github.com/nsf/termbox-go (download)
github.com/jgautheron/codename-generator (download)
github.com/nu7hatch/gouuid (download)
github.com/docker/docker/api/types/blkiodev
github.com/docker/docker/api/types/mount
github.com/docker/docker/api/types/strslice
github.com/docker/docker/vendor/github.com/docker/go-connections/nat
github.com/docker/docker/vendor/github.com/docker/go-units
github.com/docker/docker/api/types/versions
github.com/docker/docker/api/types/network
github.com/docker/docker/api/types/filters
github.com/docker/docker/api/types/registry
github.com/docker/docker/vendor/github.com/Sirupsen/logrus
github.com/docker/docker/api/types/container
github.com/docker/docker/pkg/system
github.com/docker/docker/vendor/github.com/opencontainers/runc/libcontainer/user
github.com/docker/docker/vendor/golang.org/x/net/context
github.com/docker/docker/api/types/swarm
github.com/docker/docker/pkg/ioutils
github.com/docker/docker/api/types
github.com/docker/docker/pkg/idtools
github.com/docker/docker/pkg/promise
github.com/docker/docker/pkg/pools
github.com/docker/docker/pkg/fileutils
github.com/docker/docker/vendor/github.com/opencontainers/runc/libcontainer/system
github.com/docker/docker/pkg/homedir
github.com/docker/docker/vendor/github.com/Nvveen/Gotty
github.com/docker/docker/pkg/jsonlog
github.com/docker/docker/opts
github.com/docker/docker/pkg/archive
github.com/docker/docker/pkg/term
github.com/docker/docker/pkg/stdcopy
github.com/docker/go-units
github.com/hashicorp/go-cleanhttp
github.com/docker/docker/pkg/jsonmessage
golang.org/x/net/context
github.com/maruel/panicparse/stack
golang.org/x/net/context/ctxhttp
github.com/mattn/go-runewidth
github.com/nsf/termbox-go
github.com/fsouza/go-dockerclient
github.com/gizak/termui
github.com/bcicen/ctop/widgets
github.com/bcicen/ctop/widgets/menu
github.com/bcicen/ctop/metrics
github.com/bcicen/ctop/cwidgets
github.com/bcicen/ctop/cwidgets/compact
github.com/bcicen/ctop/cwidgets/expanded
# github.com/bcicen/ctop/cwidgets/expanded
Code/Go/src/github.com/bcicen/ctop/cwidgets/expanded/info.go:19: p.Seperator undefined (type *termui.Table has no field or method Seperator)
Code/Go/src/github.com/bcicen/ctop/cwidgets/expanded/mem.go:73: mbar.NumFmt undefined (type *termui.MBarChart has no field or method NumFmt)
```

**Comment by francislavoie** [comment] 2017-03-10 00:31
Duplicate of https://github.com/bcicen/ctop/issues/16

**Closed** 2017-03-10 01:33 UTC
