### ISSUE TITLE
Cpu usage doesn't work on ubuntu 21.10

### ISSUE THREAD

**Issue by ZeusFSX** [bcicen/ctop#288] opened 2022-02-03 12:09 UTC
Cpu usage doesn't work on ubuntu 21.10 (impish), show 0%
![image](https://user-images.githubusercontent.com/22007867/152339924-83ceaa5e-6ef7-49fa-bf3b-01a0d22229d9.png)

But if I run it via docker it works 
![image](https://user-images.githubusercontent.com/22007867/152340683-56bb10a4-a7e5-451c-8438-9211c2cad168.png)

**Comment by NemesisRE** [comment] 2022-02-10 01:29
And no IO R/W 

`ctop version 0.7.6, build 8f0c9f5 go1.16.5`
`Docker version 20.10.12, build e91ed57`
`Linux 5.13.0-28-generic #31-Ubuntu SMP Thu Jan 13 17:41:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by plague-doctor** [comment] 2022-02-10 04:04
Exactly the same on Debian Bullseye :-(

**Comment by jakubfrieb** [comment] 2022-03-01 13:35
I have the same on 
Manjaro Kernel 5.16.7
Docker version 20.10.12, build e91ed5707e
ctop version dev-build, build none go1.16.5

And also you can notice that memory usage is differ from `docker stats` command 
![image](https://user-images.githubusercontent.com/7541799/156177870-9056d15b-6275-4f8f-bf1b-84518219b2bb.png)

And last thing if I try open Single View I ended with 

![image](https://user-images.githubusercontent.com/7541799/156178477-dbde85f2-24e4-4671-a80b-4c96e133288e.png)

**Comment by Flova** [comment] 2022-03-04 02:10
Duplicate of #276. Fixed in #281 but not released yet by the maintainer.

**Comment by bcicen** [comment] 2022-03-23 17:33
this is resolved in the [latest release](https://github.com/bcicen/ctop/releases/tag/v0.7.7); feel free to reopen if otherwise

**Closed as completed by bcicen** 2022-03-23 17:33 UTC
